### ISSUE TITLE
Speak button broken

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/text-to-speech-nodejs#14]
In Firefox (40.0.3 - IBM CCK), if I visit http://text-to-speech-demo.mybluemix.net/ and click the red Speak button, it logs the following:

    InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable

The error appears to be coming from the [`audio.currentTime=0`](https://github.com/watson-developer-cloud/text-to-speech-nodejs/blob/master/public/js/demo.js#L51) line.

Chrome appears to work fine.

**Comment by daniel-bolanos** [comment]
Thank you for fixing this @nfriedly, this was an annoying bug.

Dani
