### ISSUE TITLE
Ogg Vorbis vs Ogg Opus

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/text-to-speech-nodejs#15]
The [docs](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/text-to-speech/overview.shtml#overview) (and my experience a while back) indicate that the service only supports Ogg containers with the Opus codec but the [demo](http://text-to-speech-demo.mybluemix.net/) says "The audio is returned in the Ogg Vorbis format which..." 

(FWIW, I'd love to see *both* codecs supported - some of the IoT hardware I wanted to do a demo with supports Ogg Vorbis but not Ogg Opus.)

**Comment by nfriedly** [comment]
I double checked the codec info in VLC, it's Opus. So I corrected it on the home page, merged `master` into `livedemo`, and updated the demo.

**Comment by daniel-bolanos** [comment]
Thank you for this correction @nfriedly . One question, how bad do you need Ogg Vorbis for your IoT projects? We might be able to support that if it is important.

Dani

**Comment by nfriedly** [comment]
Now that the service supports FLAC, its not as big of an issue, but it'd still be nice to have - there are a lot of different modules similar to https://www.adafruit.com/product/1790 that support Ogg Vorbis.
