### ISSUE TITLE
Speech should start playing before it finishes downloading

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/text-to-speech-nodejs#3]
The service supports streaming of audio, however on both Chrome and Firefox wait until the entire download is finished before they begin playing, creating a lot of lag. Our old demo did not had this bug (it started playing immediately although the slider position was incorrect, since it didn't know the file size).

**Comment by germanattanasio** [comment]
Fixed in 36ff72002b965888dc0907b8c080cd4ecf7dfdb6
