### ISSUE TITLE
Should have visual feedback while waiting for speech

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/text-to-speech-nodejs#4]
Pressing "Speak" results in no user-visible feedback until the entire download is finished and speech begins. This can often take 10-20 seconds, resulting in a bad user experience. As soon as the Speak button is pressed there should be some visual indication that the request was sent and is waiting for the server.

**Comment by germanattanasio** [comment]
Fixed in 36ff72002b965888dc0907b8c080cd4ecf7dfdb6
