### ISSUE TITLE
local deployment without bluemix account?!

### ISSUE THREAD

**Issue by zenny** [watson-developer-cloud/text-to-speech-nodejs#55]
Just curious whether this could be deployed as a local instance without bluemix account?

Appreciate if somebody point it to documentation of the kind. Thanks!

**Comment by nfriedly** [comment]
Hi @zenny 

At this point in time, the Watson APIs are only accessible through Bluemix - so you can deploy the app locally, but you still have to have a Bluemix account to get service credentials.
