### ISSUE TITLE
es-US male?

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/text-to-speech-nodejs#56]
http://181.135.63.86:3003/

Is possible have male for spanish es-US?

**Comment by daniel-bolanos** [comment]
Hello @johnfelipe

what is http://181.135.63.86:3003/?

**Comment by nfriedly** [comment]
No, not at the moment. You can see a complete list of available voices [in the documentation](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/text-to-speech/using.shtml#voices) or by [calling the API](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/text-to-speech/api/v1/#voices_methods)
