### ISSUE TITLE
No error message when incorrect SSML input value is specified

### ISSUE THREAD

**Issue by kkeerthana** [watson-developer-cloud/text-to-speech-nodejs#57]
Specifying an incorrect SSML input value and downloading the audio file seems to break it.
(I get an error message as expected when I click on 'Speak' instead).

Examples:
<break time='300 ms'/>
<prosody rate='xyz'>

**Comment by nfriedly** [comment]
Hi @kkeerthana, thanks for pointing this out.

This case is a bit tricky because the demo streams the download directly from the service, so it can't read that there was an error until it's too late. I'll see if I can find a good workaround, but it may take some time.

**Comment by kognate** [comment]
This is fixed in #71 and and should be deployed soon
