### ISSUE TITLE
Redeploy the demo

### ISSUE THREAD

**Issue by Lhuihui** [watson-developer-cloud/text-to-speech-nodejs#58]
Hi, German&James, I've updated the navigation link, service icon and favicon. Please help redeploy the demo :-)

**Comment by daniel-bolanos** [comment]
guys, we have a new release of STT + demo coming out today, please do not redeploy anything today (leave it for tomorrow), thanks a lot

**Comment by germanattanasio** [comment]
@daniel-bolanos are saying that you will be updating the demo today?

**Comment by daniel-bolanos** [comment]
yes, STT and TTS demos will be updated today

**Comment by nfriedly** [comment]
oh, shoot, sorry. The STT demo automatically deployed, and I just set up auto deployment for this one before I noticed this. Do we need to roll it back?

**Comment by nfriedly** [comment]
(Only `master` auto-deploys, and then only after the tests pass)
