### ISSUE TITLE
First syllable is lost in created audio after it's downloaded

### ISSUE THREAD

**Issue by Atreilly** [watson-developer-cloud/text-to-speech-nodejs#59]
1) Issue: First syllable is lost in created audio after it's downloaded, for all en-US English voices, and some other voices.

Example text: 
tomato, tomato, tomato.

Allision voice and most languages
After pressing, "Download" and listening ...
Expected: tomato, tomato, tomato
Actual: mato, tomato, tomato  (note: first syllable of first word is missing)

Alexandra

**Comment by germanattanasio** [comment]
How do we fix this ?

**Comment by nfriedly** [comment]
What browser are you using? What media player? Can you post a copy of the file online somewhere (or just email it to me - nfriedly@us.ibm.com)

I just tested in a few browsers and was unable to reproduce the issue. Playback in VLC is choppy at first, but if I queue up multiple files, only the first second or so of audio is choppy regardless of which file it comes from. Playback in Firefox or Chrome (by opening the file) is flawless.

This is one of the files I created during testing - can you try with it and confirm if it plays back properly on your system? https://ibm.box.com/s/tyyfsy8xsnfv5eqvwb2rhx58re788e47

**Comment by kognate** [comment]
I can reproduce it.  

https://ibm.box.com/s/rgb0v8c9ggwnuj298cln8chz47uqnlpz

I converted it to wav and looked at the wavform and it's clipped in the data.

**Comment by kognate** [comment]
This seems to be a VLC problem because looking at the output wavform the audio is all there and correct.
