### ISSUE TITLE
TTS Demo --  "Too many requests, please try again later.", when I press "Speak" button too often

### ISSUE THREAD

**Issue by Atreilly** [watson-developer-cloud/text-to-speech-nodejs#61]
Issue: TTS Demo -- Too many requests, please try again later. 
When I make about 5 updates to the text box in a minute, I get an error message: "Too many requests, please try again later."

or when I press the "Speak" button, too often (23 times in a row), I get an error message: "Too many requests, please try again later." (See attachment for a screen shot after this test).

Expected: No error message
Actual:  I get an error message: "Too many requests, please try again later."

Alexandra
[TTS Demo -- Too many requests, please try again later on June 28 2016.zip](https://github.com/watson-developer-cloud/text-to-speech-nodejs/files/338449/TTS.Demo.--.Too.many.requests.please.try.again.later.on.June.28.2016.zip)

**Comment by germanattanasio** [comment]
We have rate limitation in place. The error is expected
