### ISSUE TITLE
"SyntaxError: Unexpected token : "on running node app.js

### ISSUE THREAD

**Issue by chackerian** [watson-developer-cloud/text-to-speech-nodejs#62]
I'm getting an error while trying to start the node server:

 

>    "credentials": {
>                  ^
> SyntaxError: Unexpected token :
>     at exports.runInThisContext (vm.js:73:16)
>     at Module._compile (module.js:443:25)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Function.Module.runMain (module.js:501:10)
>     at startup (node.js:129:16)
>     at node.js:814:3

My app.js looks like the following and the username and password field are filled in properly

> {
    "credentials": {
        "url": "https://stream.watsonplatform.net/text-to-speech/api",
        "password": "passwordhere",
        "username": "usernamehere"
    }
}

**Comment by chackerian** [comment]
I'm also getting this error when I try to run the server on Bluemix. Probably I'm just confused about how the app.js file supposed to be structured.

**Comment by germanattanasio** [comment]
When running locally you only need to replace `username` and `password` [here](https://github.com/watson-developer-cloud/text-to-speech-nodejs/blob/master/app.js#L30-L31) with your service credentials.

**Comment by chackerian** [comment]
I did that

**Comment by nfriedly** [comment]
Can you email me a copy of the file? nfriedly@us ibm.com

**Comment by nfriedly** [comment]
Sorry, typing on a phone, that should be @us.ibm.com
