### ISSUE TITLE
ETA on non-supported tags?

### ISSUE THREAD

**Issue by Boundarybreaker** [watson-developer-cloud/text-to-speech-nodejs#63]
I'm making a voice file that requires emphasis on some words and audio clips to be played, but neither of those features are supported. Do you know either A) when those features will become supported or B) what other programs I can use that **do** support those features?

**Comment by daniel-bolanos** [comment]
Hi @Boundarybreaker, Maria, will answer this one...

**Comment by smithme** [comment]
Hi @Boundarybreaker,  our system does not currently support the specification of word emphasis.  This is something that we are working on but I don't have a date to provide to you as to when this feature will become available.

**Comment by germanattanasio** [comment]
This is now supported by the service, see: http://www.ibm.com/watson/developercloud/doc/text-to-speech/SSML.shtml
