### ISSUE TITLE
failed to with "deploy to Bluemix"

### ISSUE THREAD

**Issue by josepmao** [watson-developer-cloud/text-to-speech-nodejs#67]
When click "deploy to bluemix" button, succeed in 
- create project
- clone repository
- config pipeline
but failed during deploy
<img width="828" alt="screen shot 2016-09-28 at 12 25 22 pm" src="https://cloud.githubusercontent.com/assets/15610849/18901407/f6dc84c0-858d-11e6-8d51-492183a32bd3.png">

**Comment by daniel-bolanos** [comment]
missing a comma, fixed now

**Comment by josepmao** [comment]
Thanks Daniel
