### ISSUE TITLE
Service failing using a dedicated Bluemix account. 

### ISSUE THREAD

**Issue by bacarell** [watson-developer-cloud/text-to-speech-nodejs#68]
I am getting a challenge to enter ID information to pass through a Watson gateway when trying to use the demo application.  In Bluemix Public, I am able to provide my user information and use the service; however, when I try to access the service using a Bluemix dedicated account, my credentials do not work.  Assistance would be  most appreciated.

**Comment by germanattanasio** [comment]
Hey @bacarell make sure you specify the `username` `password` and `url`. In your case the `url` is different because you are using a dedicated environment.
Check this line: https://github.com/watson-developer-cloud/text-to-speech-nodejs/blob/master/app.js#L32
