### ISSUE TITLE
Downloading an audio file with an error in the input text gives a "File not found" and crashes

### ISSUE THREAD

**Issue by kkeerthana** [watson-developer-cloud/text-to-speech-nodejs#73]
This issue was marked as fixed & closed earlier, but I still see it - https://github.com/watson-developer-cloud/text-to-speech-nodejs/issues/57

Example:
1. Select "American English (en-US): Allison (female, expressive, transformable)"
2. Go to the "Expressive SSML" 
3. Enter this text: \<speak> Hello World
4. Click on Download

I see this (Firefox):

<img width="669" alt="screen shot 2016-12-02 at 10 57 53 am" src="https://cloud.githubusercontent.com/assets/8869904/20840477/5f6bc1ae-b87e-11e6-926a-730407166eca.png">

Let me know if you have any questions.
Thanks!

**Comment by germanattanasio** [comment]
The way we trigger the file download is by changing the `window.location` in your browser. We can't catch that error which you will see if you click on `Speak`

```
Input contains unmatched open SSML tags

```
