### ISSUE TITLE
Spanish Is not working today

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/text-to-speech-nodejs#75]
How can test all in spanish, only spanish?

**Comment by germanattanasio** [comment]
I just tried and it's working. What browser are you using @johnfelipe ?

**Comment by johnfelipe** [comment]
i mean, transformable

**Comment by daniel-bolanos** [comment]
Hi @johnfelipe , the Spanish voices are not transformable, that feature is not yet available.
