### ISSUE TITLE
"Speak" button is disabled in Safari

### ISSUE THREAD

**Issue by kkeerthana** [watson-developer-cloud/text-to-speech-nodejs#89]
The "Speak" button in https://text-to-speech-demo.ng.bluemix.net/ is disabled in Safari.
It works fine in Firefox and Chrome.

<img width="837" alt="image" src="https://user-images.githubusercontent.com/8869904/36609807-256b33d4-189c-11e8-8bcd-a2e7e54be57b.png">

**Comment by germanattanasio** [comment]
This is working as designed.
