### ISSUE TITLE
Language translator V2 or V3 ?

### ISSUE THREAD

**Issue by PhilippeComte** [watson-developer-cloud/text-to-speech-nodejs#95]
Hello , Is this demo already  using the Language Translation V3 service ? 
Or is it  still on V2 ?  
I cannot find an entry for TTS V3 in the current Watson SDK . 
Is there a a way to bypass that ? 
Thank you

**Comment by germanattanasio** [comment]
There is no v3 for Text to speech. This demo is using v1 which is the latest version. See https://console.bluemix.net/docs/services/speech-to-text/release-notes.html#release-notes
